language: ruby
rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
before_script:
  - mysql -e 'create database `test-tracker_test`;'
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
script: CODECLIMATE_REPO_TOKEN=794dc02f8b73798fec0fb6559cb3f81d799a6539b59c69dc95db74e3d8218546 bundle exec rspec --tag ~no_travis spec
bundler_args: --without production
cache: bundler
