<% db_socket = ENV['DEV_MYSQL_SOCKET'] || '/tmp/mysql.sock' %>

default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: BugBashTracker
  password: hWUPRwV4FezEOWCqsywPYYTL
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  username: root
  database: BugBashTracker_development
  socket: <%= db_socket %>
  password:

test:
  <<: *default
  username: root
  database: BugBashTracker_test
  socket: <%= db_socket %>
  password:

production:
  <<: *default
  database: BugBashTracker_production

