<% db_socket = ENV['DEV_MYSQL_SOCKET'] || '/tmp/mysql.sock' %>

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  username: root
  database: BugBashTracker_development
  socket: <%= db_socket %>
  password:

test:
  <<: *default
  username: root
  database: BugBashTracker_test
  password:

# production:
#   <<: *default
#   database: BugBashTracker_production

